version: "3.7"

services:
  backend:
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    image: reachip/devops-backend:1.0.0
    container_name: backend
    networks:
      - app-network
    depends_on:
      - database
      - httpd

  database:
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"
    image: reachip/devops-database:1.0.0
    container_name: postgres
    networks:
      - app-network

  httpd:
    ports:
      - "80:80"
    image: reachip/devops-httpd:1.0.0
    container_name: webserver
    networks:
      - app-network

  frontend:
    ports:
      - "9090:80"
    image: reachip/devops-frontend:1.0.0
    container_name: frontend
    networks:
      - app-network

  prometheus:
    image: reachip/devops-prometheus:1.0.0
    container_name: prometheus
    networks:
      - app-network
    restart: always
    ports:
      - "7070:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    container_name: grafana
    networks:
      - app-network
    ports:
      - "3000:3000"
    build: grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

networks:
  app-network:
