scrape_configs:
  - job_name: 'Application backend'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'backend:80' ]
        labels:
          application: 'Application backend'
          
