scrape_configs:
  - job_name: 'Simulateur'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'backend:80' ]
        labels:
          application: 'Simulateur Spring Boot Application'

  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:7070" ]

