all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ansible.tp.key
    postgres_password: pwd
    postgres_user: usr
    postgres_db: db
    network: app-network
  children:
    prod:
      hosts: centos@rached.mejri.takima.cloud
